sudo: required
dist: trusty

services:
- docker

install:
- docker-compose -f docker-compose-testing.yml pull
- docker-compose -f docker-compose-testing.yml build

script:
- docker-compose -f docker-compose-testing.yml run --no-deps --rm web python3 manage.py test
- docker-compose -f docker-compose-testing.yml run --no-deps --rm angular npm run test
- docker-compose -f docker-compose-testing.yml up --abort-on-container-exit
