# before run use command `docker volume create postgres`
# run docker-compose -f docker-compose-win.yml up
version: "3"
services:
  web:
    build: .
    container_name: web01
    env_file:
      - ./.env
    command: >
            sh -c "python3 manage.py collectstatic --no-input &&
            python3 manage.py makemigrations &&
            python3 manage.py migrate &&
            gunicorn config.wsgi -b 0.0.0.0:8000 --workers 3 --timeout 600"
    volumes:
      - .:/www
    ports:
      - "8000:8000"
    depends_on:
      - db

  db:
    container_name: db01
    image: "postgres:10.5-alpine"
    restart: always
    env_file:
      - ./.env
    ports:
      - "5432:5432"
    volumes:
      - postgres:/var/lib/postgresql/data

  adminer:
    container_name: adminer01
    image: adminer
    restart: always
    ports:
      - "8080:8080"
    env_file:
      - ./.env

  nginx:
    container_name: nginx01
    image: nginx:latest
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - ./media:/var/www/quran-words/media
      - ./collected_static:/var/www/quran-words/collected_static
    ports:
      - "80:80"
    depends_on:
      - web

volumes:
  postgres:
    external: true
