version: "3"
services:
  web:
    build: ./django/
    restart: on-failure
    environment:
      - ALLOWED_HOSTS=*
      - DJANGO_SECRET_KEY=SomeKey
      - DJANGO_EXECUTION_ENVIRONMENT=DEVELOPMENT
      - DEBUG=1
    command: sh -c "python3 manage.py migrate && python3 manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./django/:/www
    expose:
      - "8000"

  angular:
    depends_on:
      - "web"
    build:
      context: ./frontend
      dockerfile: TestDockerfile
    expose:
      - "4200"
    volumes:
      - ./frontend/angular/dist:/usr/src/app/dist
    command: ng e2e
