# before run use command `docker volume create postgres`
# run docker-compose -f docker-compose-win.yml up
version: "3"
services:
  web:
    build: .
    container_name: web
    env_file:
      - ./.env
    entrypoint: "/www/entrypoint.sh"
    command: "gunicorn config.wsgi -b 0.0.0.0:8000 --workers 3 --timeout 600"
    volumes:
      - .:/www
    expose:
      - "8000"
    depends_on:
      - db

  db:
    container_name: db
    image: "postgres:10.5-alpine"
    restart: always
    env_file:
      - ./.env
    expose:
      - "5432"
    volumes:
      - postgres:/var/lib/postgresql/data

  adminer:
    container_name: adminer
    image: adminer
    restart: always
    ports:
      - "8080:8080"
    env_file:
      - ./.env

  nginx:
    container_name: nginx
    image: nginx:latest
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - ./media:/var/www/quran-words/media
      - ./collected_static:/var/www/quran-words/collected_static
    ports:
      - "80:80"
    depends_on:
      - web

volumes:
  postgres:
    external: true
