version: "3"
services:
  backend:
    build: ./backend/
    restart: on-failure
    environment:
      - SECRET_KEY=secret123
      - DEBUG=1
      - ALLOWED_HOSTS=*
    command: python3 manage.py runserver 0.0.0.0:8000
    volumes:
      - ./backend/:/www
    ports:
      - "8000:8000"
